using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EkipProjesi.Core.RehabilitasyonMerkezleri
{
    public class IHastaBagimlilikSiddetiFormlari
    {
        public int ID { get; set; }
        public int HastaID { get; set; }
        public string HastaNo { get; set; }
        public int Ulke { get; set; }
        public int Merkez { get; set; }
        public int Program { get; set; }
        public int Modalite { get; set; }
        public string ModaliteAciklama { get; set; }
        public int G3Soru { get; set; }
        public DateTime BasvuruTarihi { get; set; }
        public DateTime GorusmeTarihi { get; set; }
        public TimeSpan BaslamaSaati { get; set; }
        public TimeSpan BitisSaati { get; set; }
        public int Sinif { get; set; }
        public int IletisimSekli { get; set; }
        public int Cinsiyet { get; set; }
        public string G11Soru { get; set; }
        public int G14Yil { get; set; }
        public int G14Ay { get; set; }
        public DateTime DogumTarihi { get; set; }
        public int Yas { get; set; }
        public int G19Soru { get; set; }
        public string G19Aciklama { get; set; }
        public string G20Soru { get; set; }
        public string SevkKaynagi { get; set; }
        public string GenelBilgiKaynagi { get; set; }
        public string GenelBilgiKaynagiDiger { get; set; }
        public int M1Soru { get; set; }
        public int M3Soru { get; set; }
        public string M3SoruAciklama { get; set; }
        public int M4Soru { get; set; }
        public int M5Soru { get; set; }
        public string M5SoruAciklama { get; set; }
        public int M6Soru { get; set; }
        public int M7Soru { get; set; }
        public int M8Soru { get; set; }
        public string M8SoruAciklama { get; set; }
        public int M10Soru { get; set; }
        public int M11Soru { get; set; }
        public int M12Soru { get; set; }
        public int M12aSoru { get; set; }
        public int M12bSoru { get; set; }
        public int M13Soru { get; set; }
        public int M13aSoru { get; set; }
        public int M13bSoru { get; set; }
        public int M14Soru { get; set; }
        public int M14aSoru { get; set; }
        public int M14bSoru { get; set; }
        public string TibbiDurumNotlar { get; set; }
        public int E1Yil { get; set; }
        public int E1Ay { get; set; }
        public int TamamlanmisEgitimSuresiDuzey { get; set; }
        public string E1aSoruAciklama { get; set; }
        public int E2Soru { get; set; }
        public int E4aSoru { get; set; }
        public int E6SoruYil { get; set; }
        public int E6SoruAy { get; set; }
        public int E7Soru { get; set; }
        public int E9Soru { get; set; }
        public int E10Soru { get; set; }
        public int E11Soru { get; set; }
        public string IsIstihdamNotlar { get; set; }
        public int E12Soru { get; set; }
        public int E13Soru { get; set; }
        public int E14Soru { get; set; }
        public int E15Soru { get; set; }
        public int E16Soru { get; set; }
        public int E17Soru { get; set; }
        public int E18Soru { get; set; }
        public string E19Soru { get; set; }
        public int E20Soru { get; set; }
        public int E21Soru { get; set; }
        public int E23Soru { get; set; }
        public int E24Soru { get; set; }
        public string KonuEdilenParaBirimi { get; set; }
        public string IstihdamNotlari { get; set; }
        public string D1Soru { get; set; }
        public int D1Yil { get; set; }
        public int D1Yol { get; set; }
        public string D2Soru { get; set; }
        public int D2Yil { get; set; }
        public int D2Yol { get; set; }
        public string D3Soru { get; set; }
        public int D3Yil { get; set; }
        public int D3Yol { get; set; }
        public string D4Soru { get; set; }
        public int D4Yil { get; set; }
        public int D4Yol { get; set; }
        public string D5Soru { get; set; }
        public int D5Yil { get; set; }
        public int D5Yol { get; set; }
        public string D6Soru { get; set; }
        public int D6Yil { get; set; }
        public int D6Yol { get; set; }
        public string D7Soru { get; set; }
        public int D7Yil { get; set; }
        public int D7Yol { get; set; }
        public string D8Soru { get; set; }
        public int D8Yil { get; set; }
        public int D8Yol { get; set; }
        public string D9Soru { get; set; }
        public int D9Yil { get; set; }
        public int D9Yol { get; set; }
        public string D10Soru { get; set; }
        public int D10Yil { get; set; }
        public int D10Yol { get; set; }
        public string D11Soru { get; set; }
        public int D11Yil { get; set; }
        public int D11Yol { get; set; }
        public string D12Soru { get; set; }
        public int D12Yil { get; set; }
        public int D12Yol { get; set; }
        public string D13Soru { get; set; }
        public int D13Yil { get; set; }
        public int D13Yol { get; set; }
        public string D14aSoru { get; set; }
        public string D14bSoru { get; set; }
        public int D15Soru { get; set; }
        public string D16Soru { get; set; }
        public int D17Soru { get; set; }
        public string AlkolMaddeNotu { get; set; }
        public string AlkolMaddeNotuD5 { get; set; }
        public int D38Soru { get; set; }
        public string D38aSoru { get; set; }
        public int D19aSoru { get; set; }
        public string D21aSoru { get; set; }
        public int D23Soru { get; set; }
        public int D24Soru { get; set; }
        public int D25Soru { get; set; }
        public int D26Soru { get; set; }
        public string D26SoruAciklama { get; set; }
        public int D28Soru { get; set; }
        public int D30Soru { get; set; }
        public int D27Soru { get; set; }
        public string D27SoruAciklama { get; set; }
        public int D29Soru { get; set; }
        public int D31Soru { get; set; }
        public int D34Soru { get; set; }
        public int D35Soru { get; set; }
        public int D36Soru { get; set; }
        public string D37Soru { get; set; }
        public int D37SoruYil { get; set; }
        public int D37SoruYol { get; set; }
        public int D39Soru { get; set; }
        public int D39a { get; set; }
        public int D39b { get; set; }
        public int D39c { get; set; }
        public int D39d { get; set; }
        public int D39e { get; set; }
        public string AlkolMaddeNotlari { get; set; }
        public int L1Soru { get; set; }
        public int L2Soru { get; set; }
        public int L3Soru { get; set; }
        public int L4Soru { get; set; }
        public int L5Soru { get; set; }
        public int L6Soru { get; set; }
        public int L7Soru { get; set; }
        public int L8Soru { get; set; }
        public int L9Soru { get; set; }
        public int L10Soru { get; set; }
        public int L11Soru { get; set; }
        public int L12Soru { get; set; }
        public int L13Soru { get; set; }
        public int L14Soru { get; set; }
        public int L15Soru { get; set; }
        public string L16Soru { get; set; }
        public string L17Soru { get; set; }
        public int L18Soru { get; set; }
        public int L19Soru { get; set; }
        public int L20Soru { get; set; }
        public int L21Soru { get; set; }
        public int L24Soru { get; set; }
        public string L25Soru { get; set; }
        public int L26Soru { get; set; }
        public int L27Soru { get; set; }
        public int L28Soru { get; set; }
        public int L29Soru { get; set; }
        public int L31Soru { get; set; }
        public int L32Soru { get; set; }
        public string HukikiNotlar { get; set; }
        public string HukikiNotlarDevami { get; set; }
        public int F1Soru { get; set; }
        public string F1SoruAciklama { get; set; }
        public int F3Soru { get; set; }
        public int F4Soru { get; set; }
        public int F6Soru { get; set; }
        public int F4aSoru { get; set; }
        public int F7Soru { get; set; }
        public int F8Soru { get; set; }
        public int F9Soru { get; set; }
        public int F10Soru { get; set; }
        public string F11aSoru { get; set; }
        public int F18Soru { get; set; }
        public int F18SoruYasam { get; set; }
        public int F19Soru { get; set; }
        public int F19SoruYasam { get; set; }
        public int F20Soru { get; set; }
        public int F20SoruYasam { get; set; }
        public int F21Soru { get; set; }
        public int F21SoruYasam { get; set; }
        public int F22Soru { get; set; }
        public int F22SoruYasam { get; set; }
        public int F23Soru { get; set; }
        public int F23SoruYasam { get; set; }
        public string F23SoruAciklama { get; set; }
        public int F24Soru { get; set; }
        public int F24SoruYasam { get; set; }
        public int F25Soru { get; set; }
        public int F25SoruYasam { get; set; }
        public int F26Soru { get; set; }
        public int F26SoruYasam { get; set; }
        public string AileSosyalDurumNotlar { get; set; }
        public int F28Soru { get; set; }
        public int F28SoruYasam { get; set; }
        public int F29Soru { get; set; }
        public int F29SoruYasam { get; set; }
        public int F30Soru { get; set; }
        public int F32Soru { get; set; }
        public int F34Soru { get; set; }
        public int F31Soru { get; set; }
        public int F33Soru { get; set; }
        public int F35Soru { get; set; }
        public int F37Soru { get; set; }
        public int F38Soru { get; set; }
        public int F39Soru1 { get; set; }
        public int F39Soru2 { get; set; }
        public int F39aSoru1 { get; set; }
        public int F39aSoru2 { get; set; }
        public string AileSosyalDurumNotlarDevami { get; set; }
        public int P1Soru { get; set; }
        public int P2Soru { get; set; }
        public int P3Soru { get; set; }
        public int P4Soru { get; set; }
        public int P4SoruYasam { get; set; }
        public int P5Soru { get; set; }
        public int P5SoruYasam { get; set; }
        public int P6Soru { get; set; }
        public int P6SoruYasam { get; set; }
        public int P7Soru { get; set; }
        public int P7SoruYasam { get; set; }
        public int P8Soru { get; set; }
        public int P8SoruYasam { get; set; }
        public int P9Soru { get; set; }
        public int P9SoruYasam { get; set; }
        public int P10Soru { get; set; }
        public int P10SoruYasam { get; set; }
        public int P11Soru { get; set; }
        public int P11SoruYasam { get; set; }
        public int P12Soru { get; set; }
        public int P13Soru { get; set; }
        public int P14Soru { get; set; }
        public int P22Soru { get; set; }
        public int P23Soru { get; set; }
        public string PsikiyatrikNotlar { get; set; }
        public int G12SonNokta { get; set; }
        public int G50TedaviKodu { get; set; }
        public string G50TedaviAciklama { get; set; }
        public string GenelYorumlar { get; set; }
        public int KaydedenKullaniciID { get; set; }
        public DateTime KayitTarihi { get; set; }
    }
}