//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketCevaplari
    {
        public long ID { get; set; }
        public long SoruID { get; set; }
        public string CevapAdi { get; set; }
        public int Puan { get; set; }
    }
}
