//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketTipleri
    {
        public int ID { get; set; }
        public string TipAdi { get; set; }
        public string Aciklama { get; set; }
        public bool Status { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int UserID { get; set; }
    }
}
