//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnketSorulari
    {
        public long ID { get; set; }
        public long GrupID { get; set; }
        public long AnketID { get; set; }
        public long SoruID { get; set; }
        public bool ZorunluMu { get; set; }
        public int SoruTipi { get; set; }
        public double Agirlik { get; set; }
        public int CevapSayisi { get; set; }
    }
}
