//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketler
    {
        public long ID { get; set; }
        public int IsletmeID { get; set; }
        public int AnketTipID { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int UserID { get; set; }
        public bool Status { get; set; }
    }
}
