//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArindirmaBasvuruBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArindirmaBasvuruBilgileri()
        {
            this.HastaBeyanBilgileri = new HashSet<HastaBeyanBilgileri>();
        }
    
        public int ID { get; set; }
        public int KurumKodu { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string HastaProtokolNo { get; set; }
        public Nullable<System.DateTime> PoliklinikMuayeneTarihSaati { get; set; }
        public string MuayeneyiGerceklestirenHekim { get; set; }
        public string MuayeneyiGerceklestirenHekimTuru { get; set; }
        public string MaddeBilgisi { get; set; }
        public string EslikEdenHastalikOykusu { get; set; }
        public string PsikiyatrikHastalikOykusuAciklama { get; set; }
        public Nullable<bool> PsikiyatrikHastalikOykusu { get; set; }
        public string KullanmaktaOlduguDigerIlacBilgisi { get; set; }
        public string SonBasvurudanSonraAlkolMaddeKullanimiOlmusMu { get; set; }
        public string SonBasvurudanSonraOnerilenIlaclariDuzenliKullanmisMi { get; set; }
        public Nullable<bool> YoksunlukBulgusu { get; set; }
        public Nullable<bool> IntoksikasyonBulgusu { get; set; }
        public Nullable<bool> IdrarToksikolojiBulgusu { get; set; }
        public Nullable<System.DateTime> LogTarihi { get; set; }
        public Nullable<System.DateTime> GuncellemeTarihi { get; set; }
        public string HastaEkipNo { get; set; }
        public Nullable<int> PoliklinikTuruID { get; set; }
        public string BeyanAdresi { get; set; }
        public string BeyanTelefonu { get; set; }
        public Nullable<int> KararID { get; set; }
    
        public virtual ArindirmaBasvuruKararlari ArindirmaBasvuruKararlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaBeyanBilgileri> HastaBeyanBilgileri { get; set; }
    }
}
