//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruBilgileriLabSonuc
    {
        public string ID { get; set; }
        public string KurumKodu { get; set; }
        public Nullable<System.DateTime> LabNumuneAlimTarihi { get; set; }
        public Nullable<System.DateTime> LabNumuneSonucTarihi { get; set; }
        public Nullable<bool> MaddeBulgusu { get; set; }
    }
}
