//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelYuklemeleri
    {
        public long ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> ExcelTuru { get; set; }
        public Nullable<int> SatirSayisi { get; set; }
        public Nullable<int> Durum { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> HataliSatirSayisi { get; set; }
        public string ExcelID { get; set; }
    }
}
