//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FizikselHastalikOykuleri
    {
        public int HastalikOykusuID { get; set; }
        public string HastaProtokolNo { get; set; }
        public Nullable<bool> Yok { get; set; }
        public Nullable<bool> DM { get; set; }
        public Nullable<bool> Hipertansiyon { get; set; }
        public Nullable<bool> Astim { get; set; }
        public Nullable<bool> Epilepsi { get; set; }
        public Nullable<bool> HIV { get; set; }
        public Nullable<bool> BobrekYetmezligi { get; set; }
        public Nullable<bool> Siroz { get; set; }
        public Nullable<bool> Hepatit { get; set; }
        public string HepatitAciklama { get; set; }
        public Nullable<bool> KalpHastaligi { get; set; }
        public string KalpHastaligiAciklama { get; set; }
        public Nullable<bool> IlacAlerjisi { get; set; }
        public string IlacAlerjisiAciklama { get; set; }
        public Nullable<bool> Diger { get; set; }
        public string DigerAciklama { get; set; }
        public int KurumKodu { get; set; }
        public Nullable<System.DateTime> LogTarihi { get; set; }
        public string HastaEkipNo { get; set; }
    }
}
