//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaIlkKayitBilgileri
    {
        public int ID { get; set; }
        public int HastaID { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string KurumTuru { get; set; }
        public string KaydedenKurum { get; set; }
        public string VakaBilgiKaynagi { get; set; }
        public string EldeEdilenBilgiler { get; set; }
    
        public virtual Hastalar Hastalar { get; set; }
    }
}
