//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaMaddeKullanimBilgileri
    {
        public int ID { get; set; }
        public int KurumKodu { get; set; }
        public string HastaProtokolNo { get; set; }
        public string MaddeTuru { get; set; }
        public string Sure { get; set; }
        public Nullable<bool> KullanimSuresiAy { get; set; }
        public Nullable<bool> KullanimSuresiYil { get; set; }
        public string Miktar { get; set; }
        public string Yontem { get; set; }
        public string Siklik { get; set; }
        public string EnSonKullanmaZamani { get; set; }
        public Nullable<bool> EnSonKullanmaZamaniGun { get; set; }
        public Nullable<bool> EnSonKullanmaZamaniAy { get; set; }
        public Nullable<bool> EnSonKullanmaZamaniYil { get; set; }
        public string HastaEkipNo { get; set; }
    }
}
