//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaBaharFormlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HastaBaharFormlari()
        {
            this.HastaBaharFormuSonuc = new HashSet<HastaBaharFormuSonuc>();
        }
    
        public int ID { get; set; }
        public int HastaID { get; set; }
        public Nullable<int> CalismaDurumu { get; set; }
        public Nullable<int> EkonomikDurumu { get; set; }
        public string YasadigiIl { get; set; }
        public string YasadigiIlce { get; set; }
        public Nullable<int> GorusmeninYapildigiMerkez { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string YakinAdiSoyadi { get; set; }
        public string YakinTelefonu { get; set; }
        public Nullable<int> GelisSekli { get; set; }
        public Nullable<int> TedaviBasvuruNedeni { get; set; }
        public string SonTedaviBasvuruNedeni { get; set; }
        public Nullable<int> S1TutunUrunleri { get; set; }
        public Nullable<int> S1AlkolluIcecekler { get; set; }
        public Nullable<int> S1Esrar { get; set; }
        public Nullable<int> S1Kokain { get; set; }
        public Nullable<int> S1AmfctaminTipiUyaricilar { get; set; }
        public Nullable<int> S1Inhalanlar { get; set; }
        public Nullable<int> S1Sakinlestiriciler { get; set; }
        public Nullable<int> S1Halüsinojenler { get; set; }
        public Nullable<int> S1Opioidler { get; set; }
        public Nullable<int> S1Diger { get; set; }
        public string S1DigerAciklama { get; set; }
        public Nullable<int> S2TutunUrunleri { get; set; }
        public Nullable<int> S2AlkolluIcecekler { get; set; }
        public Nullable<int> S2Esrar { get; set; }
        public Nullable<int> S2Kokain { get; set; }
        public Nullable<int> S2AmfctaminTipiUyaricilar { get; set; }
        public Nullable<int> S2Inhalanlar { get; set; }
        public Nullable<int> S2Sakinlestiriciler { get; set; }
        public Nullable<int> S2Halüsinojenler { get; set; }
        public Nullable<int> S2Opioidler { get; set; }
        public Nullable<int> S2Diger { get; set; }
        public string S2DigerAciklama { get; set; }
        public Nullable<int> S3TutunUrunleri { get; set; }
        public Nullable<int> S3AlkolluIcecekler { get; set; }
        public Nullable<int> S3Esrar { get; set; }
        public Nullable<int> S3Kokain { get; set; }
        public Nullable<int> S3AmfctaminTipiUyaricilar { get; set; }
        public Nullable<int> S3Inhalanlar { get; set; }
        public Nullable<int> S3Sakinlestiriciler { get; set; }
        public Nullable<int> S3Halüsinojenler { get; set; }
        public Nullable<int> S3Opioidler { get; set; }
        public Nullable<int> S3Diger { get; set; }
        public string S3DigerAciklama { get; set; }
        public Nullable<int> S4TutunUrunleri { get; set; }
        public Nullable<int> S4AlkolluIcecekler { get; set; }
        public Nullable<int> S4Esrar { get; set; }
        public Nullable<int> S4Kokain { get; set; }
        public Nullable<int> S4AmfctaminTipiUyaricilar { get; set; }
        public Nullable<int> S4Inhalanlar { get; set; }
        public Nullable<int> S4Sakinlestiriciler { get; set; }
        public Nullable<int> S4Halüsinojenler { get; set; }
        public Nullable<int> S4Opioidler { get; set; }
        public Nullable<int> S4Diger { get; set; }
        public string S4DigerAciklama { get; set; }
        public Nullable<int> S5TutunUrunleri { get; set; }
        public Nullable<int> S5AlkolluIcecekler { get; set; }
        public Nullable<int> S5Esrar { get; set; }
        public Nullable<int> S5Kokain { get; set; }
        public Nullable<int> S5AmfctaminTipiUyaricilar { get; set; }
        public Nullable<int> S5Inhalanlar { get; set; }
        public Nullable<int> S5Sakinlestiriciler { get; set; }
        public Nullable<int> S5Halüsinojenler { get; set; }
        public Nullable<int> S5Opioidler { get; set; }
        public Nullable<int> S5Diger { get; set; }
        public string S5DigerAciklama { get; set; }
        public Nullable<int> S6TutunUrunleri { get; set; }
        public Nullable<int> S6AlkolluIcecekler { get; set; }
        public Nullable<int> S6Esrar { get; set; }
        public Nullable<int> S6Kokain { get; set; }
        public Nullable<int> S6AmfctaminTipiUyaricilar { get; set; }
        public Nullable<int> S6Inhalanlar { get; set; }
        public Nullable<int> S6Sakinlestiriciler { get; set; }
        public Nullable<int> S6Halüsinojenler { get; set; }
        public Nullable<int> S6Opioidler { get; set; }
        public Nullable<int> S6Diger { get; set; }
        public string S6DigerAciklama { get; set; }
        public string TamAyiklikBaslamaZamani { get; set; }
        public Nullable<bool> Suboxone { get; set; }
        public string SuboxoneAciklama { get; set; }
        public Nullable<bool> NaltreksonImplant { get; set; }
        public string NaltreksonImplantAciklama { get; set; }
        public Nullable<bool> Ethylex { get; set; }
        public string EthylexAciklama { get; set; }
        public Nullable<bool> Campral { get; set; }
        public string CampralAciklama { get; set; }
        public Nullable<bool> Antabus { get; set; }
        public string AntabusAciklama { get; set; }
        public string TedaviAciklama { get; set; }
        public Nullable<int> PlanlananRehabilitasyonProgrami { get; set; }
        public Nullable<int> PlanlananProgramSuresi { get; set; }
        public Nullable<int> ProgramGunleri { get; set; }
        public string BelirlenenTerapist { get; set; }
        public string Hedefler { get; set; }
        public Nullable<int> KaydedenKullaniciID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaBaharFormuSonuc> HastaBaharFormuSonuc { get; set; }
        public virtual Hastalar Hastalar { get; set; }
    }
}
