//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaIskurGorusmeleri
    {
        public int ID { get; set; }
        public int HastaID { get; set; }
        public string GorusmeyiYapanDanisman { get; set; }
        public Nullable<System.DateTime> GorusmeTarihi { get; set; }
        public Nullable<int> GorusmeSonucu { get; set; }
        public string YonlendirilenIsyeri { get; set; }
        public Nullable<System.DateTime> YonlendirmeBasvuruTarihi { get; set; }
        public Nullable<int> IsyeriYonlendirmeSonuc { get; set; }
        public string IseBasladigiYer { get; set; }
        public Nullable<System.DateTime> IseBaslamaTarihi { get; set; }
        public string IseBaslamaNedeni { get; set; }
        public Nullable<int> IsKulubuYonlendirmeSonuc { get; set; }
        public Nullable<System.DateTime> PlanlananBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> PlanlananSurecBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> SurecBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> SurecTamamlanmaTarihi { get; set; }
        public Nullable<int> IsKulubuYonlendirmeDurum { get; set; }
        public string SertifikaDosyaYolu { get; set; }
        public Nullable<int> Tur { get; set; }
        public Nullable<int> ProgramDurum { get; set; }
        public string PlanlananProgramTuru { get; set; }
        public Nullable<System.DateTime> PlanlananProgramBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> PlanlananProgramBaslangici { get; set; }
        public Nullable<int> ProgramTuru { get; set; }
        public Nullable<System.DateTime> ProgramTuruTamamlanmaTarihi { get; set; }
        public string YonlendirilenKursTuru { get; set; }
        public string YonlendirilenKursBilgisiTuru { get; set; }
        public string GorusmeSonucuDiger { get; set; }
        public Nullable<System.DateTime> GorusmeKayitTarihi { get; set; }
        public Nullable<int> KaydedenKullaniciID { get; set; }
    
        public virtual Hastalar Hastalar { get; set; }
    }
}
