//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaOlceklerFormu
    {
        public int ID { get; set; }
        public int HastaID { get; set; }
        public Nullable<int> DikkatEksikligi { get; set; }
        public Nullable<int> AsiriHareketlilik { get; set; }
        public Nullable<int> UykuSoru1 { get; set; }
        public Nullable<int> UykuSoru2 { get; set; }
        public Nullable<int> UykuSoru3 { get; set; }
        public Nullable<int> UykuSoru4 { get; set; }
        public Nullable<int> UykuSoru5 { get; set; }
        public Nullable<int> UykuSoru6 { get; set; }
        public Nullable<int> UykuSoru7 { get; set; }
        public Nullable<int> UykuSoru8 { get; set; }
        public Nullable<int> UykuSoru9 { get; set; }
        public Nullable<int> UykuSoru10 { get; set; }
        public Nullable<int> UykuBozukluguTanisi { get; set; }
        public Nullable<int> KadinFormu1 { get; set; }
        public Nullable<int> KadinFormu2 { get; set; }
        public Nullable<int> KadinFormu3 { get; set; }
        public Nullable<int> KadinFormu4 { get; set; }
        public Nullable<int> KadinFormu5 { get; set; }
        public Nullable<int> ErkekFormu1 { get; set; }
        public Nullable<int> ErkekFormu2 { get; set; }
        public Nullable<int> ErkekFormu3 { get; set; }
        public Nullable<int> ErkekFormu4 { get; set; }
        public Nullable<int> ErkekFormu5 { get; set; }
        public Nullable<int> TravmatikYasam1 { get; set; }
        public Nullable<int> TravmatikYasam2 { get; set; }
        public Nullable<int> TravmatikYasam3 { get; set; }
        public Nullable<int> TravmatikYasam4 { get; set; }
        public Nullable<int> TravmatikYasam5 { get; set; }
        public Nullable<int> TravmatikYasam6 { get; set; }
        public Nullable<int> TravmatikYasam7 { get; set; }
        public Nullable<int> TravmatikYasam8 { get; set; }
        public Nullable<int> TravmatikYasam9 { get; set; }
        public Nullable<int> TravmatikYasam10 { get; set; }
        public Nullable<int> TravmatikYasam11 { get; set; }
        public Nullable<int> TravmatikYasam12 { get; set; }
        public Nullable<int> TravmatikYasam13 { get; set; }
        public Nullable<int> TravmatikYasam14 { get; set; }
        public string TravmatikYasam14Aciklama { get; set; }
        public Nullable<int> Appendix1 { get; set; }
        public Nullable<int> Appendix2 { get; set; }
        public Nullable<int> Appendix3 { get; set; }
        public Nullable<int> Appendix4 { get; set; }
        public Nullable<int> Appendix5 { get; set; }
        public Nullable<int> Appendix6 { get; set; }
        public Nullable<int> Appendix7 { get; set; }
        public Nullable<int> Appendix8 { get; set; }
        public Nullable<int> Appendix9 { get; set; }
        public Nullable<int> Appendix10 { get; set; }
        public Nullable<int> Appendix11 { get; set; }
        public Nullable<int> Appendix12 { get; set; }
        public Nullable<int> Appendix13 { get; set; }
        public Nullable<int> Appendix14 { get; set; }
        public Nullable<int> Appendix15 { get; set; }
        public Nullable<int> Appendix16 { get; set; }
        public Nullable<int> Appendix17 { get; set; }
        public Nullable<int> Appendix18 { get; set; }
        public Nullable<int> Appendix19 { get; set; }
        public Nullable<int> Appendix20 { get; set; }
        public Nullable<int> KaydedenKullaniciID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        public virtual Hastalar Hastalar { get; set; }
    }
}
