//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstihdamIsyeriGorusmeleri
    {
        public int ID { get; set; }
        public int IsyeriID { get; set; }
        public string GorusmeyiYapanKisi { get; set; }
        public string GorusulenKisi { get; set; }
        public string GorusmedeEleAlinanKonular { get; set; }
        public System.DateTime GorusmeTarihi { get; set; }
        public Nullable<int> KaydedenKullaniciID { get; set; }
    
        public virtual IstihdamIsyerleri IstihdamIsyerleri { get; set; }
    }
}
