//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstihdamIsyeriIletisimKisileri
    {
        public int ID { get; set; }
        public int IsyeriID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Unvan { get; set; }
        public string Telefon { get; set; }
        public string EPosta { get; set; }
        public string Adres { get; set; }
        public Nullable<int> KaydedenKullaniciID { get; set; }
    
        public virtual IstihdamIsyerleri IstihdamIsyerleri { get; set; }
    }
}
