//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstihdamIsyeriAdresBilgisi
    {
        public int ID { get; set; }
        public int IsyeriID { get; set; }
        public string Sokak { get; set; }
        public string Cadde { get; set; }
        public string Bina_No { get; set; }
        public string Daire_No { get; set; }
        public Nullable<int> IlID { get; set; }
        public Nullable<int> IlceID { get; set; }
        public Nullable<int> MahalleID { get; set; }
    
        public virtual Il Il { get; set; }
        public virtual Ilce Ilce { get; set; }
        public virtual IstihdamIsyerleri IstihdamIsyerleri { get; set; }
    }
}
