//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciIzinBilgileri
    {
        public int ID { get; set; }
        public int KullaniciID { get; set; }
        public int IzinTuruId { get; set; }
        public System.DateTime BaslamaTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public Nullable<int> ToplamIzinSuresi { get; set; }
        public string IzinAdresi { get; set; }
        public string Aciklama { get; set; }
        public int YerineBakacakKisiId { get; set; }
        public Nullable<bool> IzinDurumu { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<int> KaydedenKullaniciId { get; set; }
        public Nullable<int> AktarimID { get; set; }
        public Nullable<int> AktarimPersonelID { get; set; }
        public string YerineBakacakKisiAd { get; set; }
    }
}
