//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciIzinTuru
    {
        public int ID { get; set; }
        public string TurAdi { get; set; }
        public int IsletmeId { get; set; }
        public bool Status { get; set; }
        public int Enum { get; set; }
    }
}
