//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KurumPoliklinikTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KurumPoliklinikTurleri()
        {
            this.RandevuBilgileri = new HashSet<RandevuBilgileri>();
            this.RandevuAyarlari = new HashSet<RandevuAyarlari>();
        }
    
        public int ID { get; set; }
        public int KurumID { get; set; }
        public string PoliklinikTuru { get; set; }
    
        public virtual Kurumlar Kurumlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandevuBilgileri> RandevuBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandevuAyarlari> RandevuAyarlari { get; set; }
    }
}
