//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KurumRandevulari
    {
        public int ID { get; set; }
        public string HastaEkipNo { get; set; }
        public int KurumKodu { get; set; }
        public string RandevuTipi { get; set; }
        public System.DateTime RandevuTarihSaati { get; set; }
        public Nullable<bool> GeldiGelmedi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    }
}
