//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogHataBildirimleri
    {
        public long ID { get; set; }
        public string Konu { get; set; }
        public string Mesaj { get; set; }
        public int UserID { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string HTML { get; set; }
        public string FileFormat { get; set; }
        public byte[] ScreenShot { get; set; }
        public Nullable<bool> CozumDurumu { get; set; }
        public string CozumMesajı { get; set; }
    }
}
