//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogLoginIslemleri
    {
        public long ID { get; set; }
        public int KullaniciId { get; set; }
        public int LogTipi { get; set; }
        public System.DateTime Tarih { get; set; }
        public string IP { get; set; }
        public string IsletimSistemi { get; set; }
        public string TarayiciAdi { get; set; }
        public string MobilMi { get; set; }
        public string SessionID { get; set; }
        public string MachineName { get; set; }
        public string MachineIP { get; set; }
    }
}
