//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesajGidenKullanici
    {
        public int ID { get; set; }
        public Nullable<int> MesajId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
