//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobilEkipVakaFormlari
    {
        public int ID { get; set; }
        public int HastaID { get; set; }
        public string Adres { get; set; }
        public string Nitelik { get; set; }
        public Nullable<bool> BilgiKaynagiKendisi { get; set; }
        public Nullable<bool> BilgiKaynagiAnne { get; set; }
        public Nullable<bool> BilgiKaynagiBaba { get; set; }
        public Nullable<bool> BilgiKaynagiEs { get; set; }
        public Nullable<bool> BilgiKaynagiCocuk { get; set; }
        public Nullable<bool> BilgiKaynagiKardes { get; set; }
        public Nullable<bool> BilgiKaynagiArkadas { get; set; }
        public Nullable<bool> BilgiKaynagiAkraba { get; set; }
        public Nullable<bool> BilgiKaynagiDiger { get; set; }
        public string BilgiKaynagiAkrabaAciklama { get; set; }
        public string BilgiKaynagiDigerAciklama { get; set; }
        public string GenelTanitim { get; set; }
        public string MaddeyeBaslamaYasi { get; set; }
        public string IlkKullandigiMadde { get; set; }
        public string SuAndaKullandigiMaddeler { get; set; }
        public Nullable<int> MaddeKullanimSikligi { get; set; }
        public string MaddeyeBaslamaNedeni { get; set; }
        public string EnSonMaddeKullanimZamani { get; set; }
        public string KurumBilgisiVarMi { get; set; }
        public Nullable<bool> MotivasyonKaynagiAile { get; set; }
        public Nullable<bool> MotivasyonKaynagiEkonomi { get; set; }
        public Nullable<bool> MotivasyonKaynagiSaglik { get; set; }
        public Nullable<bool> MotivasyonKaynagiDiger { get; set; }
        public string MotivasyonKaynagiDigerAciklama { get; set; }
        public Nullable<int> BagimlilikEvresi { get; set; }
        public Nullable<int> TedaviyeYaklasimi { get; set; }
        public Nullable<int> MotivasyonDuzeyi { get; set; }
        public string MaddeDigerTespitler { get; set; }
        public Nullable<int> OgrenimDurumu { get; set; }
        public Nullable<int> LiseTuru { get; set; }
        public string Fakulte { get; set; }
        public string Bolum { get; set; }
        public string EgitimDigerTespitler { get; set; }
        public Nullable<int> GecimKaynagi { get; set; }
        public string YaptigiIs { get; set; }
        public string CalistigiYer { get; set; }
        public string CalismaSuresi { get; set; }
        public Nullable<int> Maas { get; set; }
        public string CalismaSahasi { get; set; }
        public Nullable<int> AylikOrtCalistigiGunSayisi { get; set; }
        public string CalismaBilgisiDiger { get; set; }
        public Nullable<int> AylikOrtGelir { get; set; }
        public string AylikOrtGelirDuzeyi { get; set; }
        public string AileAylikOrtGelirDuzeyi { get; set; }
        public Nullable<int> IkametDurumu { get; set; }
        public string TopluIkametDetay { get; set; }
        public string IkametDiger { get; set; }
        public Nullable<int> EnUzunCalismaSuresi { get; set; }
        public string EkonomikDurumDiger { get; set; }
        public string EslikEdenBedenselHastaliklar { get; set; }
        public string EslikEdenRuhsalHastaliklar { get; set; }
        public string PlanliTedaviPlani { get; set; }
        public string DigerBagimlilikTuru { get; set; }
        public string SaglikDigerTespitler { get; set; }
        public Nullable<int> AdliDurumu { get; set; }
        public string AdliDurumDiger { get; set; }
        public string AileSosyalYasantisi { get; set; }
        public string DegerlendirmeVeSonuc { get; set; }
        public Nullable<int> DevamEtmemeNedeni { get; set; }
        public string DevamEtmemeNedeniAciklama { get; set; }
        public Nullable<int> Karar { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<int> KaydedenKullaniciID { get; set; }
    
        public virtual Hastalar Hastalar { get; set; }
    }
}
