//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelFotograflar
    {
        public int ID { get; set; }
        public int PersonelID { get; set; }
        public byte[] FileByte { get; set; }
        public string ContentType { get; set; }
        public bool Status { get; set; }
    }
}
