//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliklinikTurleri
    {
        public int ID { get; set; }
        public int KurumKodu { get; set; }
        public string PoliklinikAdi { get; set; }
        public int AktifOdaSayisi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public System.DateTime LogTarihi { get; set; }
    }
}
