//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandevuBilgileri
    {
        public int ID { get; set; }
        public string Aciklama { get; set; }
        public string Renk { get; set; }
        public Nullable<bool> TumGun { get; set; }
        public string HastaTCKimlikNo { get; set; }
        public string HastaAdi { get; set; }
        public string HastaSoyadi { get; set; }
        public string Telefon { get; set; }
        public System.DateTime RandevuBaslangicTarihi { get; set; }
        public System.DateTime RandevuBitisTarihi { get; set; }
        public int KurumID { get; set; }
        public int PoliklinikTuruID { get; set; }
        public string YakinTelefonu { get; set; }
        public string RandevuDurumu { get; set; }
        public System.TimeSpan RandevuBaslangicSaati { get; set; }
        public System.TimeSpan RandevuBitisSaati { get; set; }
        public Nullable<int> KaydedenKullaniciID { get; set; }
        public Nullable<int> GuncelleyenKullaniciID { get; set; }
    
        public virtual Kurumlar Kurumlar { get; set; }
        public virtual KurumPoliklinikTurleri KurumPoliklinikTurleri { get; set; }
    }
}
