//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VakaTanilari112
    {
        public int ID { get; set; }
        public int Vaka112ID { get; set; }
        public Nullable<int> TaniKoduID { get; set; }
    
        public virtual TaniKodlari TaniKodlari { get; set; }
        public virtual VakaBilgileri112 VakaBilgileri112 { get; set; }
    }
}
