//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VakaBilgileri112
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VakaBilgileri112()
        {
            this.VakaTanilari112 = new HashSet<VakaTanilari112>();
        }
    
        public int ID { get; set; }
        public int KurumKodu { get; set; }
        public string HastaTCKimlikNo { get; set; }
        public string HastaEkipNo { get; set; }
        public string HastaAdi { get; set; }
        public string HastaSoyadi { get; set; }
        public Nullable<System.DateTime> CagriTarihSaati { get; set; }
        public string OnTani { get; set; }
        public string YapilanIslem { get; set; }
        public string BirakildigiKurum { get; set; }
        public string AlindigiYer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VakaTanilari112> VakaTanilari112 { get; set; }
    }
}
