//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yatislar
    {
        public int ID { get; set; }
        public int KurumKodu { get; set; }
        public System.DateTime YatisTarihi { get; set; }
        public string GunlukIzlemBilgisi { get; set; }
        public Nullable<System.DateTime> YatisSonlanmaTarihi { get; set; }
        public Nullable<int> YatisSonlanmaID { get; set; }
        public string YatisSonlanmaAciklama { get; set; }
        public Nullable<System.DateTime> LogTarihi { get; set; }
        public string HastaEkipNo { get; set; }
        public Nullable<int> KararID { get; set; }
    
        public virtual YatisSonlanmaNedenleri YatisSonlanmaNedenleri { get; set; }
        public virtual ArindirmaBasvuruKararlari ArindirmaBasvuruKararlari { get; set; }
    }
}
