//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkipProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEDAMHastaBilgileri
    {
        public int ID { get; set; }
        public string HastaTCKimlikNo { get; set; }
        public string HastaEkipNo { get; set; }
        public string HastaAdi { get; set; }
        public string HastaSoyadi { get; set; }
        public Nullable<System.DateTime> BasvuruTarihi { get; set; }
        public string BasvuruTuru { get; set; }
        public string BasvurudaYapilanIslemler { get; set; }
        public string BasvuruDegerlendirmeNotlari { get; set; }
    }
}
